service: cert-transparency

plugins:
  # Plugin to allow IAM role per function rather than per service
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'default'}
  region: ${file(infra/terraform.tfvars.json):aws_region.${self:provider.stage}}
  versionFunctions: false
  logRetentionInDays: 1

custom:
  awsRegion: ${self:provider.region}

  bucketName: ${ssm:/${self:service.name}/${self:provider.stage}/s3bucket_domains}
  dbTableName: ${ssm:/${self:service.name}/${self:provider.stage}/dynamodb_temp}
  query_que_arn: ${ssm:/${self:service.name}/${self:provider.stage}/sqs_query_logs_arn}
  db_read_queue_arn: ${ssm:/${self:service.name}/${self:provider.stage}/sqs_query_db_arn}

  tldCacheFile: "/opt/python/tldextract/.tld_set_snapshot"  # this allows tldextract to use built-in snapshot

functions:
  query_logs:
    handler: query_logs.query_to_db
    timeout: 240
    memorySize: 2048
    layers:
      - arn:aws:lambda:${self:custom.awsRegion}:113088814899:layer:Klayers-python37-aiohttp:4
      - arn:aws:lambda:${self:custom.awsRegion}:113088814899:layer:Klayers-python37-pyOpenSSL:1
      - arn:aws:lambda:${self:custom.awsRegion}:113088814899:layer:Klayers-python37-tldextract:1
      - arn:aws:lambda:${self:custom.awsRegion}:113088814899:layer:Klayers-python37-construct:1
    environment:
      bucket_name: ${self:custom.bucketName}
      db_table_name: ${self:custom.dbTableName}
      TLDEXTRACT_CACHE: ${self:custom.tldCacheFile}
    iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:PutItem
      - dynamodb:BatchWriteItem
      Resource:
        Fn::Join:
        - ""
        - - "arn:aws:dynamodb:"
          - ${self:custom.awsRegion}
          - ":"
          - { Ref: "AWS::AccountId" }
          - ":table/"
          - ${self:custom.dbTableName}
    - Effect: Allow
      Action:
      - sqs:ReceiveMessage
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
      Resource: ${self:custom.query_que_arn}
    events:
    - sqs:
        arn: ${self:custom.query_que_arn}
        batchSize: 1
    reservedConcurrency: 10
  ### Query DB #####
  query_db:
    handler: query_db.main
    timeout: 30
    memorySize: 256
    environment:
      bucket_name: ${self:custom.bucketName}
      db_table_name: ${self:custom.dbTableName}
    iamRoleStatements:
    - Effect: Allow
      Action:
      - s3:PutObject
      - s3:GetObject
      - s3:DeleteObject
      - s3:PutObjectAcl
      - s3:GetObjectAcl  # ACL permissions required for file_upload
      - s3:AbortMultipartUpload
      Resource:
        Fn::Join:
        - ""
        - - "arn:aws:s3:::"
          - ${self:custom.bucketName}
          - "/*"
    - Effect: Allow
      Action:
      - dynamodb:Query
      - dynamodb:BatchGetItem
      - dynamodb:Scan
      Resource:
        Fn::Join:
        - ""
        - - "arn:aws:dynamodb:"
          - ${self:custom.awsRegion}
          - ":"
          - { Ref: "AWS::AccountId" }
          - ":table/"
          - ${self:custom.dbTableName}
    - Effect: Allow
      Action:
      - sqs:ReceiveMessage
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
      Resource: ${self:custom.db_read_queue_arn}
    events:
    - sqs:
        arn: ${self:custom.db_read_queue_arn}
        batchSize: 1
    reservedConcurrency: 30

package:
  exclude:
    - node_modules/**
    - .serverless
    - venv/**
    - package.json
    - package-lock.json
    - .gitignore
    - requirements.txt
    - test.json
    - infra/**
    - __pychache__/**
    - .idea/**
    - config.json
    - client/**